apiVersion: v1
data:
  a: bc
  # KEYCLOAK_USER: a2V5Y2xvYWs=
  # KEYCLOAK_PASSWORD: a2V5Y2xvYWs=
  # KC_DB: cG9zdGdyZXM=
  # # KC_DB_URL: amRiYzpwb3N0Z3JlczovL2tleWNsb2FrLXBvc3RncmVzOjU0MzIva2V5Y2xvYWs=
  # KC_DB_USERNAME: a2V5Y2xvYWs=
  # KC_DB_PASSWORD: a2V5Y2xvYWs=

  #  - name: KC_DB_URL_HOST
  #       valueFrom:
  #         secretKeyRef:
  #           name: keycloak-auth
  #           key: KC_DB_URL_HOST
  #     - name: KC_DB_URL_PORT
  #       valueFrom:
  #         secretKeyRef:
  #           name: keycloak-auth
  #           key: KC_DB_URL_PORT
  #     - name: KC_DB_URL_DATABASE
  #       valueFrom:
  #         secretKeyRef:
  #           name: keycloak-auth
  #           key: KC_DB_URL_DATABASE
  #     - name: KC_DB_URL_DATABASE
  #       valueFrom:
  #         secretKeyRef:
  #           name: keycloak-auth
  #           key: KC_DB_URL_DATABASE
  # KC_DB_URL_HOST: a2V5Y2xvYWstcG9zdGdyZXM=
  # KC_DB_URL_PORT: NTQzMg== # 5432
  # KC_DB_URL_DATABASE: a2V5Y2xvYWs= # keycloak

kind: Secret
metadata:
  name: keycloak-auth
  labels:
    app: baw-project
    type: keycloak
type: Opaque
