apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  labels:
    app: baw-project
    type: keycloak
spec:
  containers:
  - name: keycloak
    image: quay.io/keycloak/keycloak:20.0
    args: ["start-dev"]
    resources:
      limits:
        cpu: "400m"
        memory: "1828Mi"
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
      - name: KC_DB
        value: "postgres"
      - name: KC_DB_PASSWORD
        value: "root"
      - name: KC_DB_URL
        value: "jdbc:postgresql://keycloak-postgresql:5432/keycloak"
      - name: KC_DB_URL_DATABASE
        value: "keycloak"
      - name: KC_DB_URL_HOST
        value: "keycloak-postgresql"
      - name: KC_DB_URL_PORT
        value: "5432"
      - name: KC_DB_USERNAME
        value: "root"
      - name: KEYCLOAK_ADMIN
        value: "keycloak"
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: "keycloak"
      # - name: KEYCLOAK_ADMIN
      #   valueFrom:
      #     secretKeyRef:
      #       name: keycloak-auth
      #       key: KEYCLOAK_USER
      # - name: KEYCLOAK_ADMIN_PASSWORD
      #   valueFrom:
      #     secretKeyRef:
      #       name: keycloak-auth
      #       key: KEYCLOAK_PASSWORD
      # - name: KC_DB
      #   valueFrom:
      #     secretKeyRef:
      #       name: keycloak-auth
      #       key: KC_DB
      # # - name: KC_DB_URL
      # #   valueFrom:
      # #     secretKeyRef:
      # #       name: keycloak-auth
      # #       key: KC_DB_URL
      # - name: KC_DB_URL_HOST
      #   valueFrom:
      #     secretKeyRef:
      #       name: keycloak-auth
      #       key: KC_DB_URL_HOST
      # - name: KC_DB_URL_PORT
      #   valueFrom:
      #     secretKeyRef:
      #       name: keycloak-auth
      #       key: KC_DB_URL_PORT
      # - name: KC_DB_URL_DATABASE
      #   valueFrom:
      #     secretKeyRef:
      #       name: keycloak-auth
      #       key: KC_DB_URL_DATABASE
      # - name: KC_DB_USERNAME
      #   valueFrom:
      #     secretKeyRef:
      #       name: keycloak-auth
      #       key: KC_DB_USERNAME
      # - name: KC_DB_PASSWORD
      #   valueFrom:
      #     secretKeyRef:
      #       name: keycloak-auth
      #       key: KC_DB_PASSWORD


