apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: baw-project
    type: backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: baw-project
    type: backend
