apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: baw-project
    type: backend
spec:
  containers:
  - name: backend
    image: backend:10
    imagePullPolicy: Never
    resources:
      limits:
        cpu: "200m"
        memory: "600Mi"
    ports:
    - containerPort: 5000
      protocol: TCP
    env:
      - name: MONGODB_URL
        valueFrom:
          configMapKeyRef:
            name: backend-config
            key: MONGODB_URL
      - name: KEYCLOAK_CLIENT_ID
        valueFrom:
          configMapKeyRef:
            name: backend-config
            key: KEYCLOAK_CLIENT_ID
      - name: KEYCLOAK_SERVER_URL
        valueFrom:
          configMapKeyRef:
            name: backend-config
            key: KEYCLOAK_SERVER_URL
      - name: KEYCLOAK_REALM
        valueFrom:
          configMapKeyRef:
            name: backend-config
            key: KEYCLOAK_REALM
      - name: FRONTEND_ORIGIN
        valueFrom:
          configMapKeyRef:
            name: backend-config
            key: FRONTEND_ORIGIN
