apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: baw-project
    type: frontend
spec:
  containers:
  - name: frontend
    image: frontend
    imagePullPolicy: Never
    resources:
      limits:
        cpu: "200m"
        memory: "400Mi"
    ports:
    - containerPort: 80
      protocol: TCP
